; --- 1. COMMON CONFIGS ---
[env]
platform = https://github.com/pioarduino/platform-espressif32.git
framework = arduino
lib_deps = 
    microbotsio/CodeCell
    bblanchon/ArduinoJson
    adafruit/Adafruit NeoPixel

; --- 2. PROJECTS AND ENVIRONMENTS FOR CODECELL C3 ---
[env:codecell_c3]
board = esp32-c3-devkitc-02
build_src_filter = +<xyz_3d_object_c3/> -<diabolo_c6/>

; --- 3. PROJECTS AND ENVIRONMENTS FOR CODECELL C6 ---
[env:codecell_c6]
board = esp32-c6-devkitc-1
build_src_filter = +<diabolo_c6/> -<xyz_3d_object_c6/>
; upload_port = COM6  ; <-- Fuerza a usar el puerto COM6